default_platform(:mac)

platform :mac do
  desc "Capture macOS screenshot"
  lane :mac_screenshots do
    sh("cd .. && xcodegen generate")
    scan(project: "../Epiphany.xcodeproj", scheme: "EpiphanyMacUITests")
    sh("mkdir -p ../fastlane/screenshots/mac && cp ~/Library/Containers/com.heyitsmejosh.epiphany-macos.uitests.xctrunner/Data/tmp/epiphany-mac-screenshots/*.png ../fastlane/screenshots/mac/")
  end
end
